// PSS Management System Constants

// Job Statuses
export const JOB_STATUSES = {
  ENQUIRY: 'ENQUIRY',
  QUOTED: 'QUOTED',
  DEPOSIT_DUE: 'DEPOSIT DUE',
  IN_PRODUCTION: 'IN PRODUCTION',
  DISPATCHED: 'DISPATCHED',
  COMPLETE: 'COMPLETE',
  ON_HOLD: 'ON HOLD',
  CANCELLED: 'CANCELLED'
};

export const STATUS_ORDER = [
  JOB_STATUSES.ENQUIRY,
  JOB_STATUSES.QUOTED,
  JOB_STATUSES.DEPOSIT_DUE,
  JOB_STATUSES.IN_PRODUCTION,
  JOB_STATUSES.DISPATCHED,
  JOB_STATUSES.COMPLETE
];

export const STATUS_ACTIONS = {
  [JOB_STATUSES.ENQUIRY]: { next: JOB_STATUSES.QUOTED, action: 'Send Quote' },
  [JOB_STATUSES.QUOTED]: { next: JOB_STATUSES.DEPOSIT_DUE, action: 'Confirm Order' },
  [JOB_STATUSES.DEPOSIT_DUE]: { next: JOB_STATUSES.IN_PRODUCTION, action: 'Mark Deposit Paid' },
  [JOB_STATUSES.IN_PRODUCTION]: { next: JOB_STATUSES.DISPATCHED, action: 'Mark Dispatched' },
  [JOB_STATUSES.DISPATCHED]: { next: JOB_STATUSES.COMPLETE, action: 'Mark Complete' },
  [JOB_STATUSES.COMPLETE]: { next: null, action: null },
  [JOB_STATUSES.ON_HOLD]: { next: null, action: 'Resume Job' },
  [JOB_STATUSES.CANCELLED]: { next: null, action: null }
};

// Client Tiers
export const CLIENT_TIERS = {
  PLATINUM: 'PLATINUM',
  VIP: 'VIP',
  REGULAR: 'REGULAR',
  REPEAT: 'REPEAT',
  OPPORTUNITY: 'OPPORTUNITY',
  HIGH_POTENTIAL: 'HIGH-POTENTIAL',
  WATCH: 'WATCH'
};

// Client Types (for pricing)
export const CLIENT_TYPES = {
  NEW: 'new',
  RETURN_WITHIN_6: 'return_within_6',
  RETURN_AFTER_6: 'return_after_6',
  LOYAL: 'loyal'
};

// Print Sizes
export const PRINT_SIZES = {
  SMALL: 'Small',
  MEDIUM: 'Medium',
  LARGE: 'Large',
  XLARGE: 'XLarge'
};

// Ink Coverage Levels
export const INK_COVERAGE = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  FULL: 'Full'
};

// Cloth Supply Options
export const CLOTH_SUPPLY = {
  PSS: 'PSS Supplied',
  CLIENT: 'Client Supplied'
};

// Pricing Configuration
export const PRICING = {
  // Base prices per print size
  basePrices: {
    [PRINT_SIZES.SMALL]: 350,
    [PRINT_SIZES.MEDIUM]: 450,
    [PRINT_SIZES.LARGE]: 550,
    [PRINT_SIZES.XLARGE]: 750
  },

  // Ink coverage multipliers
  coverageMultipliers: {
    [INK_COVERAGE.LOW]: 1.0,
    [INK_COVERAGE.MEDIUM]: 1.2,
    [INK_COVERAGE.HIGH]: 1.4,
    [INK_COVERAGE.FULL]: 1.6
  },

  // Colour multipliers
  colourMultipliers: {
    1: 1.0,
    2: 1.25,
    3: 1.5,
    4: 1.75,
    5: 2.0
  },

  // Shade cloth price per metre
  clothPricePerMetre: 55,

  // Screen fees per screen (one per colour)
  screenFees: {
    [CLIENT_TYPES.NEW]: 1850,
    [CLIENT_TYPES.RETURN_WITHIN_6]: 0,
    [CLIENT_TYPES.RETURN_AFTER_6]: 950,
    [CLIENT_TYPES.LOYAL]: 0
  },

  // Volume discounts
  volumeDiscounts: [
    { minQuantity: 200, discount: 0.15 },
    { minQuantity: 100, discount: 0.10 },
    { minQuantity: 50, discount: 0.05 },
    { minQuantity: 25, discount: 0.025 }
  ],

  // VAT rate
  vatRate: 0.15,

  // Minimum order
  minimumPrints: 5,

  // Default print height
  defaultPrintHeight: 1.8,

  // Standard roll length in metres
  rollLength: 50,

  // Standard cloth width
  clothWidth: 1.8,

  // Quote validity in days
  quoteValidityDays: 30,

  // Deposit percentage
  depositPercentage: 0.5
};

// Alert thresholds
export const ALERT_THRESHOLDS = {
  DEPOSIT_OVERDUE_DAYS: 5,
  QUOTE_UNANSWERED_DAYS: 7,
  DEADLINE_WARNING_DAYS: 3
};

// Company Info (default values)
export const DEFAULT_COMPANY_INFO = {
  name: 'Printed Shade Solutions',
  tagline: 'Innovative Brand Exposure Through Printed Shadenet Products',
  email: 'marketing@printedshade.co.za',
  phone: '082 331 5379',
  address: 'Unit 10, Celie Industrial Park, Celie Rd, Retreat, Cape Town',
  website: 'www.printedshade.co.za',
  bankName: '',
  accountNumber: '',
  branchCode: '',
  accountType: 'Business Current'
};

// Pre-loaded clients from spreadsheet
export const INITIAL_CLIENTS = [
  {
    id: 'client-1',
    companyName: 'Washirika 3 Oaks',
    shortName: 'W3O',
    companyType: 'Construction Company',
    contactPerson: 'Yolande Hunter',
    phone: '021 671 6250',
    email: 'yolande@w3o.co.za',
    address: '76 Strand Street, Woodstock',
    vatNumber: '4520219694',
    tier: 'PLATINUM',
    totalRevenue: 216114,
    lastOrderDate: '2025-03-27',
    totalOrders: 9,
    notes: 'PLATINUM CLIENT - Most valuable client with true partnership potential. Multi-branch operations across Cape Town and Johannesburg.',
    preferredColours: 'Green and white',
    typicalQuantity: '40+ prints per order',
    standardSizes: '2000mm x 790mm'
  },
  {
    id: 'client-2',
    companyName: 'Isipani Construction (Pty) Ltd',
    shortName: 'Isipani',
    companyType: 'Construction Company',
    contactPerson: 'Lyndall Sheldon',
    phone: '021 868 3008',
    email: 'lyndall@isipani.co.za',
    address: '',
    vatNumber: '',
    tier: 'VIP',
    totalRevenue: 125368,
    lastOrderDate: '2024-12-04',
    totalOrders: 5,
    notes: 'VIP CLIENT - Highest average order value, growing from R24k to R49k orders. Premium construction client.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-3',
    companyName: 'Tri-Star Construction',
    shortName: 'Tri-Star',
    companyType: 'Construction Company',
    contactPerson: 'Charmagne Monk',
    phone: '084 510 5692',
    email: 'charmagne@tri-star.co.za',
    address: '',
    vatNumber: '',
    tier: 'VIP',
    totalRevenue: 112010,
    lastOrderDate: '2025-06-13',
    totalOrders: 4,
    notes: 'BREAKTHROUGH CLIENT - Recent R52,900 order shows major project expansion. PLATINUM potential.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-4',
    companyName: 'Digi Worx CC',
    shortName: 'Digi Worx',
    companyType: 'Design/Media/Tech',
    contactPerson: 'Masego Mogashane',
    phone: '031 492 5642',
    email: 'masego.mogashane.co.za',
    address: '',
    vatNumber: '',
    tier: 'HIGH-POTENTIAL',
    totalRevenue: 106260,
    lastOrderDate: '2025-03-20',
    totalOrders: 1,
    notes: 'CRITICAL FOLLOW-UP - R106k tech order, zero follow-up since March. Durban-based, tech sector breakthrough.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-5',
    companyName: 'Boundary Secure Fencing PTY LTD',
    shortName: 'Boundary Secure',
    companyType: 'Construction Company',
    contactPerson: 'Bradley Oldfield',
    phone: '082 598 4410',
    email: 'brad@boundarysecure.co.za',
    address: '',
    vatNumber: '',
    tier: 'VIP',
    totalRevenue: 91911,
    lastOrderDate: '2025-04-25',
    totalOrders: 6,
    notes: 'VIP CLIENT - Consistent repeat client specializing in property development. Works with Sitari Country Estate.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-6',
    companyName: 'Remey Construction (Pty) Ltd',
    shortName: 'Remey',
    companyType: 'Construction Company',
    contactPerson: 'Marius Grobler',
    phone: '021 883 2616',
    email: 'buyer@remey.co.za',
    address: '9 Papegaai Street, Stellenbosch, 7600',
    vatNumber: '4730202969',
    tier: 'VIP',
    totalRevenue: 89125,
    lastOrderDate: '2025-02-20',
    totalOrders: 8,
    notes: 'VIP CLIENT - Most frequent client (8 orders). Stellenbosch-based, reliable repeat business.',
    preferredColours: 'One colour',
    typicalQuantity: '39 logos per order',
    standardSizes: '2m x 0.3m',
    specialInstructions: '5 prints per roll with 6.6m gaps'
  },
  {
    id: 'client-7',
    companyName: 'Terbinex (PTY) Ltd',
    shortName: 'Terbinex',
    companyType: 'Construction Company',
    contactPerson: 'Kalla Laubscher',
    phone: '079 526 4256',
    email: 'kalla@plumbcore.co.za',
    address: '',
    vatNumber: '',
    tier: 'HIGH-POTENTIAL',
    totalRevenue: 77280,
    lastOrderDate: '2024-09-16',
    totalOrders: 1,
    notes: 'CRITICAL FOLLOW-UP - R77k order, 9+ months no contact. Major construction company opportunity.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-8',
    companyName: 'JNA Group (Pty) Ltd',
    shortName: 'JNA',
    companyType: 'Construction Company',
    contactPerson: 'Tania Schoeman',
    phone: '021 919 8397',
    email: 'buyer@jnagroup.co.za',
    address: '',
    vatNumber: '',
    tier: 'VIP',
    totalRevenue: 66309,
    lastOrderDate: '2025-05-12',
    totalOrders: 6,
    notes: 'VIP CLIENT - Multi-division construction group. Consolidated entity across Projects, Group, and Thatchers.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-9',
    companyName: 'Eddie Stemmet Bouers (PTY) LTD',
    shortName: 'ESB',
    companyType: 'Construction Company',
    contactPerson: 'Denise Stoop',
    phone: '+27 23 614 1211',
    email: 'denise@esbou.co.za',
    address: '',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 62878,
    lastOrderDate: '2024-10-08',
    totalOrders: 3,
    notes: 'REPEAT CLIENT - Regional construction company, 3 orders totaling R62k. 8+ months since contact, needs reactivation.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-10',
    companyName: 'Hot 1027 Pty Limited',
    shortName: 'Hot 1027',
    companyType: 'Design/Media',
    contactPerson: 'Carmen Rocha',
    phone: '073 47 67 522',
    email: 'carmen@hot1027.co.za',
    address: '',
    vatNumber: '',
    tier: 'HIGH-POTENTIAL',
    totalRevenue: 57040,
    lastOrderDate: '2024-09-25',
    totalOrders: 1,
    notes: 'CRITICAL FOLLOW-UP - Media company, R57k order, 9 months dormant. Could unlock media sector.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-11',
    companyName: 'Growtime Construction',
    shortName: 'Growtime',
    companyType: 'Construction Company',
    contactPerson: 'Stefan Botha',
    phone: '076 022 8809',
    email: 'stefan@builderscorner.co.za',
    address: '',
    vatNumber: '',
    tier: 'HIGH-POTENTIAL',
    totalRevenue: 54270,
    lastOrderDate: '2024-01-31',
    totalOrders: 1,
    notes: 'CRITICAL RECOVERY - R54k construction order, 17 months no follow-up. Major builder relationship recovery.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-12',
    companyName: 'Multiknit (Pty) Ltd T/A Knittex',
    shortName: 'Knittex',
    companyType: 'Manufacturing',
    contactPerson: 'Annelien Van Janse Renesburg',
    phone: '082 260 6788',
    email: 'buyer@knittex.co.za',
    address: '',
    vatNumber: '',
    tier: 'REGULAR',
    totalRevenue: 53493,
    lastOrderDate: '2025-02-17',
    totalOrders: 4,
    notes: 'REGULAR CLIENT - Manufacturing sector diversification. Consistent repeat business, specialized niche.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-13',
    companyName: 'R + N Master Builders Cape',
    shortName: 'R+N',
    companyType: 'Construction Company',
    contactPerson: 'Charles Adonis',
    phone: '021 422 3580',
    email: 'charles@r-n.co.za',
    address: '',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 47656,
    lastOrderDate: '2024-08-21',
    totalOrders: 3,
    notes: 'REPEAT CLIENT - 3 orders totaling R47k. 10+ months since last contact, needs reactivation for continued business.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-14',
    companyName: 'Skyfall Development Properties (PTY) LTD',
    shortName: 'Skyfall',
    companyType: 'Property Developer',
    contactPerson: 'Stefan Louw',
    phone: '072 845 6947',
    email: 'joann@skyfall.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 41429,
    lastOrderDate: '2025-04-01',
    totalOrders: 1,
    notes: 'HIGH POTENTIAL - Large property development order. Represents growth opportunity in property sector.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-15',
    companyName: 'Capeprop Estates (Pty) Ltd',
    shortName: 'Capeprop',
    companyType: 'Property Developer',
    contactPerson: 'Malinda Fraser',
    phone: '021 701 2446',
    email: 'constantia@sothebysrealtyss.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 37620,
    lastOrderDate: '2024-03-01',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Property developer with R37k order but 16+ months dormant. Needs immediate reactivation.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-16',
    companyName: 'Faumba Holdings (Pty) Ltd t/a Longworth & Faul',
    shortName: 'Longworth & Faul',
    companyType: 'Construction Company',
    contactPerson: 'Carmen Baron',
    phone: '021 862 2120',
    email: 'buyer@longworthfaul.co.za',
    address: '16 Zuidmeer St, Huguenot, Paarl, 7646',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 37697,
    lastOrderDate: '2025-04-30',
    totalOrders: 3,
    notes: 'REPEAT CLIENT - Paarl-based client, 3 orders over time. Geographic diversification value, stable small orders.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-17',
    companyName: 'Plusnet/Geotex',
    shortName: 'Plusnet',
    companyType: 'Construction Company',
    contactPerson: 'Piet Buitendag',
    phone: '011 412 3954',
    email: 'pietbu@masterplasticsgroup.com',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 37490,
    lastOrderDate: '2024-02-23',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Industrial client R37k order, 16+ months dormant. Johannesburg presence, needs reactivation.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-18',
    companyName: 'Mimosa Arcade Holdings (Pty) Ltd',
    shortName: 'Berman Bros',
    companyType: 'Property Developer',
    contactPerson: 'Gabrielle Weinstein',
    phone: '021 439 9030',
    email: 'gabi@bermanbros.co.za',
    address: '',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 32373,
    lastOrderDate: '2024-06-20',
    totalOrders: 2,
    notes: 'REPEAT CLIENT - Property developer, part of Berman Bros Group. Two orders but needs reactivation after 12+ months.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-19',
    companyName: 'Phonic Properties (PTY) LTD',
    shortName: 'Phonic/PMA',
    companyType: 'Property Developer',
    contactPerson: 'Sollie Potgieter',
    phone: '012 809 3990',
    email: 'sollie@pmagroup.co.za',
    address: '',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 28118,
    lastOrderDate: '2025-03-10',
    totalOrders: 2,
    notes: 'REPEAT CLIENT - Part of PMA Group, Johannesburg-based. Early growth indicators, property development focus.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-20',
    companyName: 'Aview (PTY) Ltd',
    shortName: 'Aview',
    companyType: 'Property Developer',
    contactPerson: 'Jess de Kock',
    phone: '060 528 6328',
    email: 'jess@manor.life',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 27313,
    lastOrderDate: '2024-11-06',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Property developer with good R27k order. 7+ months dormant, needs follow-up for repeat business.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-21',
    companyName: 'Power Construction (Pty) Ltd',
    shortName: 'Power Construction',
    companyType: 'Construction Company',
    contactPerson: 'Zuriena Adams',
    phone: '021 907 1300',
    email: '',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 25530,
    lastOrderDate: '2024-05-10',
    totalOrders: 1,
    notes: 'OPPORTUNITY - R25k construction order, 13+ months dormant. Missing email address, needs reactivation.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-22',
    companyName: 'Base Projects',
    shortName: 'Base Projects',
    companyType: 'Construction Company',
    contactPerson: 'Shihaam Behardien',
    phone: '021 447 5507',
    email: 'buying@baseprojects.co.za',
    address: '',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 22540,
    lastOrderDate: '2024-06-25',
    totalOrders: 2,
    notes: 'REPEAT CLIENT - Two orders totaling R22k. 12+ months since last contact, needs reactivation for repeat business.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-23',
    companyName: 'Stabilid Cape Construction (Pty) Ltd',
    shortName: 'Stabilid',
    companyType: 'Construction Company',
    contactPerson: 'Michael Lombard',
    phone: '021 982 8210',
    email: 'michael@stabilidcape.co.za',
    address: '',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 21850,
    lastOrderDate: '2024-07-12',
    totalOrders: 2,
    notes: 'REPEAT CLIENT - Industrial construction client, 2 orders totaling R21k. 11+ months dormant, industrial niche focus.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-24',
    companyName: 'Nexus Building Contractors (Pty) Ltd',
    shortName: 'Nexus',
    companyType: 'Construction Company',
    contactPerson: 'Leonard le Roux',
    phone: '+264 67 313770',
    email: 'leonard.leroux@nexusgroup.com.na',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 20800,
    lastOrderDate: '2024-05-24',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Namibian client R20k order, 13+ months dormant. International expansion potential.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-25',
    companyName: 'Transline Trading (PTY) LTD',
    shortName: 'Transline',
    companyType: 'Construction Company',
    contactPerson: 'Marcel Henle',
    phone: '',
    email: 'marcelhenle@gmail.com',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 20298,
    lastOrderDate: '2025-05-12',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Recent R20k order, missing phone number. Good follow-up potential for repeat business.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-26',
    companyName: 'JDV Construction Boland',
    shortName: 'JDV',
    companyType: 'Construction Company',
    contactPerson: 'Jacques de Villiers',
    phone: '072 5206 903',
    email: 'jacques@jdv-construction.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 18400,
    lastOrderDate: '2024-05-15',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Boland region client R18k order, 13+ months dormant. Regional expansion potential.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-27',
    companyName: 'Evening Shade Properties 109 (Pty) Ltd',
    shortName: 'Evening Shade',
    companyType: 'Property Developer',
    contactPerson: 'Russell Honeywill',
    phone: '083 600 2219',
    email: 'russ.cx@gmail.com',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 17285,
    lastOrderDate: '2024-04-03',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Property developer R17k order, 14+ months dormant. Property sector reactivation needed.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-28',
    companyName: 'Wagters',
    shortName: 'Wagters',
    companyType: 'Construction Company',
    contactPerson: 'Liezel Moller',
    phone: '082 958 9304',
    email: 'info@wagters.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 16618,
    lastOrderDate: '2024-09-06',
    totalOrders: 1,
    notes: 'OPPORTUNITY - R16k order, 9+ months dormant. Decent conversion prospect if contacted promptly.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-29',
    companyName: 'Berrisford Construction',
    shortName: 'Berrisford',
    companyType: 'Construction Company',
    contactPerson: 'Sharilyn Meyer',
    phone: '021 447 9053',
    email: 'sharilyn@berrisfordconstruction.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 16158,
    lastOrderDate: '2024-09-06',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Construction client R16k order, 9+ months dormant. Good construction sector potential.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-30',
    companyName: 'Green Cube Construction',
    shortName: 'Green Cube',
    companyType: 'Construction Company',
    contactPerson: 'Marius Smit',
    phone: '082 909 2918',
    email: 'info@gc-group.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 15870,
    lastOrderDate: '2024-05-17',
    totalOrders: 1,
    notes: 'OPPORTUNITY - R15k construction order, 13+ months dormant. Email format needs verification.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-31',
    companyName: 'CS Property Group (Pty) Ltd',
    shortName: 'CS Property',
    companyType: 'Property Developer',
    contactPerson: 'Colleen Ferguson',
    phone: '021 880 2672',
    email: 'colleen@csprop.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 13668,
    lastOrderDate: '2024-02-20',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Property group R13k order, 16+ months dormant. Property sector reactivation needed.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-32',
    companyName: 'Afriline Civils',
    shortName: 'Afriline',
    companyType: 'Construction Company',
    contactPerson: 'Rhuan Marais',
    phone: '079 892 0056',
    email: 'rhuan@afriline.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 13570,
    lastOrderDate: '2024-05-08',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Civil engineering contractor R13k order, 13+ months dormant. Specialized niche potential.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-33',
    companyName: 'Trencon Construction',
    shortName: 'Trencon',
    companyType: 'Construction Company',
    contactPerson: 'Anje Coetzee',
    phone: '010 0557280',
    email: 'anje@trencon.co.za',
    address: 'Unit 9, Reserve 4, 15 Capricorn Way',
    vatNumber: '',
    tier: 'REPEAT',
    totalRevenue: 13398,
    lastOrderDate: '2024-02-08',
    totalOrders: 2,
    notes: 'REPEAT CLIENT - Two small orders totaling R13k. 16+ months dormant, needs reactivation assessment.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-34',
    companyName: 'Valley Electrical Contractors Pty Ltd',
    shortName: 'Valley Electrical',
    companyType: 'Electrical Contractor',
    contactPerson: 'Petrie Korf',
    phone: '083 452 2258',
    email: 'petrie@valleyelectrical.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 12018,
    lastOrderDate: '2025-04-02',
    totalOrders: 1,
    notes: 'OPPORTUNITY - Electrical contractor R12k order, 2+ months since contact. Specialized niche market potential.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-35',
    companyName: 'Cape Estates Building Project (Pty) Ltd',
    shortName: 'Cape Estates',
    companyType: 'Construction Company',
    contactPerson: 'Flip Le Roux',
    phone: '',
    email: 'capeconstruction@capeestates.co.za',
    address: '',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 8924,
    lastOrderDate: '2024-02-08',
    totalOrders: 1,
    notes: 'OPPORTUNITY - R8k order, missing phone number, 16+ months dormant. Low priority reactivation.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-36',
    companyName: 'Envirosails Pty Ltd TA Cape Shade CPT',
    shortName: 'Cape Shade CPT',
    companyType: 'Shade Solutions',
    contactPerson: 'Nicholas Adams',
    phone: '073 213 8163',
    email: 'engineering@capeshadecpt.co.za',
    address: '',
    vatNumber: '',
    tier: 'WATCH',
    totalRevenue: 3278,
    lastOrderDate: '2025-03-04',
    totalOrders: 1,
    notes: 'COMPETITIVE - Potential competitor in shade solutions. Small order suggests market testing. Monitor for competitive intelligence.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-37',
    companyName: 'Devmark Building (Pty) Ltd',
    shortName: 'Devmark',
    companyType: 'Construction Company',
    contactPerson: 'Shanaaz Fredericks',
    phone: '021 948 3502',
    email: 'sfredericks@devmark.co.za',
    address: '',
    vatNumber: '',
    tier: 'WATCH',
    totalRevenue: 3335,
    lastOrderDate: '2024-02-13',
    totalOrders: 1,
    notes: 'WATCH - Small R3k order, 16+ months dormant. Low priority for follow-up resources.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-38',
    companyName: 'Indawo Cape (Pty) Ltd',
    shortName: 'Indawo',
    companyType: 'Construction Company',
    contactPerson: 'Shaun Meintjies',
    phone: '076 231 9092',
    email: 'shaun@indawo.biz',
    address: '',
    vatNumber: '',
    tier: 'WATCH',
    totalRevenue: 2300,
    lastOrderDate: '2024-05-31',
    totalOrders: 1,
    notes: 'WATCH - Very small R2k order, 13+ months dormant. Monitor only, lowest priority.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-39',
    companyName: 'Plans 123 Pty Ltd',
    shortName: 'Plans 123',
    companyType: 'Construction Company',
    contactPerson: 'Anneke Schriek',
    phone: '082 470 0342',
    email: 'anneke@schriek.co.za',
    address: '',
    vatNumber: '',
    tier: 'WATCH',
    totalRevenue: 288,
    lastOrderDate: '2024-04-03',
    totalOrders: 1,
    notes: 'WATCH - Very small R288 test order, 14+ months dormant. Likely sample/test order only.',
    preferredColours: '',
    typicalQuantity: ''
  },
  {
    id: 'client-40',
    companyName: 'Martin & East',
    shortName: 'Martin & East',
    companyType: 'Construction Company',
    contactPerson: 'Cheryl Kampies',
    phone: '021 761 3474',
    email: 'buying@megroup.co.za',
    address: '3 Mercury Crescent, Hillstar, Wetton, 7780',
    vatNumber: '',
    tier: 'OPPORTUNITY',
    totalRevenue: 0,
    lastOrderDate: null,
    totalOrders: 0,
    notes: 'OPPORTUNITY - New potential client.',
    preferredColours: '',
    typicalQuantity: ''
  }
];
